### ISSUE TITLE
Invalid Drag and Drop operation under Ubuntu 13.04

### ISSUE THREAD

**Issue by FossPrime** [LeonNicholls/Fling#3]
Here is the log. Everything works fine until I try to drop anything. I did select the CC device. I'm running Kubuntu 13.04. The file has 777 permissions. No difference when ran as sudo.

```
java -jar Downloads/fling.jar 
Linux
Fling: createAndShowGUI
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 9: reading configurations from ~/.fonts.conf is deprecated.
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 9: reading configurations from ~/.fonts.conf is deprecated.
FileDrop: FileDrop: Hierarchy changed.
FileDrop: FileDrop: Drop target added to component.
FileDrop: FileDrop: Hierarchy changed.
FileDrop: FileDrop: Drop target added to component.
FileDrop: FileDrop: Hierarchy changed.
FileDrop: FileDrop: Drop target added to component.
FileDrop: FileDrop: Hierarchy changed.
FileDrop: FileDrop: Drop target added to component.
FlingFrame: address=/fe80:0:0:0:6a94:23ff:fe2f:f3ad%wlan0
FlingFrame: address=/192.168.0.140
FlingFrame: broadcast=/192.168.0.255
Aug 21, 2013 11:03:07 PM com.entertailion.java.fling.Log i
INFO: BroadcastDiscoveryClient: Starting client on address /192.168.0.255
FlingFrame: Started web server on port 8080
Aug 21, 2013 11:03:07 PM com.entertailion.java.fling.Log i
INFO: BroadcastDiscoveryClient: Broadcast client thread starting.
FileDrop: FileDrop: Hierarchy changed.
FileDrop: FileDrop: Drop target added to component.
FileDrop: FileDrop: Hierarchy changed.
FileDrop: FileDrop: Drop target added to component.
FileDrop: FileDrop: Hierarchy changed.
FileDrop: FileDrop: Drop target added to component.
FileDrop: FileDrop: Hierarchy changed.
FileDrop: FileDrop: Drop target added to component.
BroadcastDiscoveryClient: response=HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Thu, 22 Aug 2013 03:03:11 GMT
EXT:
LOCATION: http://192.168.0.38:8008/ssdp/device-desc.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 3b32aa56-1dd2-11b2-80be-a7d53bf13c17
SERVER: Linux/3.0.8-gc22f275, UPnP/1.0, Portable SDK for UPnP devices/1.6.18
X-User-Agent: redsonic
ST: urn:dial-multiscreen-org:service:dial:1
USN: uuid:b203c318-04de-779b-d6bf-cb53bfe9b487::urn:dial-multiscreen-org:service:dial:1
BOOTID.UPNP.ORG: 36
CONFIGID.UPNP.ORG: 5


BroadcastDiscoveryClient: tokens.length=13
FlingFrame: location=http://192.168.0.38:8008/ssdp/device-desc.xml
BroadcastDiscoveryClient: response=HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Thu, 22 Aug 2013 03:03:14 GMT
EXT:
LOCATION: http://192.168.0.38:8008/ssdp/device-desc.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 3b32aa56-1dd2-11b2-80be-a7d53bf13c17
SERVER: Linux/3.0.8-gc22f275, UPnP/1.0, Portable SDK for UPnP devices/1.6.18
X-User-Agent: redsonic
ST: urn:dial-multiscreen-org:service:dial:1
USN: uuid:b203c318-04de-779b-d6bf-cb53bfe9b487::urn:dial-multiscreen-org:service:dial:1
BOOTID.UPNP.ORG: 36
CONFIGID.UPNP.ORG: 5


BroadcastDiscoveryClient: tokens.length=13
FlingFrame: location=http://192.168.0.38:8008/ssdp/device-desc.xml
FlingFrame: appsUrl=http://192.168.0.38:8008/apps/
FlingFrame: modelName=Eureka Dongle
FlingFrame: ChromeCast device found: 192.168.0.38
FlingFrame: size=1
Aug 21, 2013 11:03:17 PM com.entertailion.java.fling.Log i
INFO: BroadcastDiscoveryClient: Exiting client loop.
FlingFrame: appsUrl=http://192.168.0.38:8008/apps/
FlingFrame: modelName=Eureka Dongle
FlingFrame: ChromeCast device found: 192.168.0.38
FileDrop: FileDrop: dragEnter event.
FileDrop: FileDrop: normal border saved.
FileDrop: FileDrop: drag border set.
FileDrop: FileDrop: event accepted.
FileDrop: FileDrop: dragExit event.
FileDrop: FileDrop: normal border restored.
FileDrop: FileDrop: dragEnter event.
FileDrop: FileDrop: normal border saved.
FileDrop: FileDrop: drag border set.
FileDrop: FileDrop: event accepted.
FileDrop: FileDrop: dragEnter event.
FileDrop: FileDrop: normal border saved.
FileDrop: FileDrop: drag border set.
FileDrop: FileDrop: event accepted.
FileDrop: FileDrop: drop event.
FileDrop: FileDrop: file list accepted.
FileDrop: FileDrop: Exception - abort:
java.awt.dnd.InvalidDnDOperationException: data translation failed
        at sun.awt.dnd.SunDropTargetContextPeer.getTransferData(SunDropTargetContextPeer.java:270)
        at sun.awt.datatransfer.TransferableProxy.getTransferData(TransferableProxy.java:73)
        at java.awt.dnd.DropTargetContext$TransferableProxy.getTransferData(DropTargetContext.java:376)
        at com.entertailion.java.fling.FileDrop$1.drop(FileDrop.java:330)
        at java.awt.dnd.DropTarget.drop(DropTarget.java:450)
        at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(SunDropTargetContextPeer.java:540)
        at sun.awt.X11.XDropTargetContextPeer.processDropMessage(XDropTargetContextPeer.java:184)
        at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(SunDropTargetContextPeer.java:854)
        at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:778)
        at sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
        at java.awt.Component.dispatchEventImpl(Component.java:4733)
        at java.awt.Container.dispatchEventImpl(Container.java:2287)
        at java.awt.Component.dispatchEvent(Component.java:4700)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4872)
        at java.awt.LightweightDispatcher.processDropTargetEvent(Container.java:4606)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4452)
        at java.awt.Container.dispatchEventImpl(Container.java:2273)
        at java.awt.Window.dispatchEventImpl(Window.java:2724)
        at java.awt.Component.dispatchEvent(Component.java:4700)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:743)
        at java.awt.EventQueue.access$400(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:694)
        at java.awt.EventQueue$3.run(EventQueue.java:691)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:713)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:220)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:135)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:123)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:119)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:111)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)
FileDrop: FileDrop: normal border restored.
Exception in thread "AWT-EventQueue-0" java.awt.dnd.InvalidDnDOperationException: invalid rejectDrop()
        at sun.awt.dnd.SunDropTargetContextPeer.rejectDrop(SunDropTargetContextPeer.java:648)
        at java.awt.dnd.DropTargetContext.rejectDrop(DropTargetContext.java:208)
        at java.awt.dnd.DropTargetDropEvent.rejectDrop(DropTargetDropEvent.java:242)
        at com.entertailion.java.fling.FileDrop$1.drop(FileDrop.java:383)
        at java.awt.dnd.DropTarget.drop(DropTarget.java:450)
        at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(SunDropTargetContextPeer.java:540)
        at sun.awt.X11.XDropTargetContextPeer.processDropMessage(XDropTargetContextPeer.java:184)
        at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(SunDropTargetContextPeer.java:854)
        at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:778)
        at sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
        at java.awt.Component.dispatchEventImpl(Component.java:4733)
        at java.awt.Container.dispatchEventImpl(Container.java:2287)
        at java.awt.Component.dispatchEvent(Component.java:4700)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4872)
        at java.awt.LightweightDispatcher.processDropTargetEvent(Container.java:4606)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4452)
        at java.awt.Container.dispatchEventImpl(Container.java:2273)
        at java.awt.Window.dispatchEventImpl(Window.java:2724)
        at java.awt.Component.dispatchEvent(Component.java:4700)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:743)
        at java.awt.EventQueue.access$400(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:694)
        at java.awt.EventQueue$3.run(EventQueue.java:691)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:713)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:220)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:135)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:123)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:119)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:111)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)
```

**Comment by wolkenschieber** [comment]
java.awt.dnd.InvalidDnDOperationException: data translation failed
        at sun.awt.dnd.SunDropTargetContextPeer.getTransferData(SunDropTargetContextPeer.java:270)
        at sun.awt.datatransfer.TransferableProxy.getTransferData(TransferableProxy.java:73)
        at java.awt.dnd.DropTargetContext$TransferableProxy.getTransferData(DropTargetContext.java:376)
        at com.entertailion.java.fling.FileDrop$1.drop(FileDrop.java:330)

I'm getting a simlar exception in another program when running it with jre8. Same operation performs fine using jre7.
The operation is dragging a file from file browser onto a panel. 

Does the problem still persisit for you and which jre are you using?
